'''
Created on 09/apr/2013

@author: Stefano Tizianel
'''
import datetime
import csv
from it_eutile_utils_properties.Constants import Constants
#from it_eutile_utils_database.ConnectionManager import ConnectionManager
from it_eutile_utils_log.LogManager import LogManager
from it_eutile_utils_csvmanager.CsvManager import CsvManager
#
import cx_Oracle

connstr = "SAP_USER" + '/' + "sap_user" + '@' + "192.168.0.177" + ':' + "1521" + '/' + "SINPROD"
conn = cx_Oracle.connect(connstr)

stat_finale = '''
SELECT ID_SR,
       TIPOLOGIA_SR,
       ID_SR_PADRE,
       ID_INTERAZIONE,
       CATEGORIA_1,
       CATEGORIA_2,
       CATEGORIA_3,
       STATO_SR,
       SEGMENTO_CLIENTE,
       CANALE_INGAGGIO,
       USER_ID_CREATORE,
       to_char(DATA_CREAZIONE, 'yyyymmddhh24miss'),
       MOTIVO_STATO,
       to_char(DATA_CHIUSURA, 'yyyymmddhh24miss'),
       to_char(DATA_ASSEGNAZIONE, 'yyyymmddhh24miss'),
       to_char(DATA_SCADENZA, 'yyyymmddhh24miss'),
       NUMERO_DOCUMENTI,
       TIPO_CORRISPONDENZA,
       TIPO_SERVIZIO,
       NOTE_CALL_CENTER,
       NOTE_CALL_CENTER_2,
       NOTE_RISERVATE_BOS,
       NOTE_RISERVATE_BOS_2,
       ATTIVITA,
       ATTIVITA_2,
       ATTIVITA_3,
       ATTIVITA_4,
       IDENTIFICATIVO_OPT,
       UTENTE_CREATORE,
       GRUPPO_CREATORE,
       CANALE,
       ID_PUNTO,
       PUNTO_FORNITURA,
       RICHIESTA_INFO,
       ID_TICKET,
       CODICE_CLIENTE,
       RAGIONE_SOCIALE,
       INDIRIZZO_MAIL,
       INDIRIZZO,
       CAP,
       COMUNE,
       PROVINCIA,
       TELEFONO,
       FAX,
       ID_PERSONA_CONTATTO,
       NOME_CONT,
       COGNOME_CONT,
       EMAIL_CONT,
       TEL_CONT,
       CELL_CONT,
       RIPROPOSIZIONE,
       P_IVA,
       COD_FISCALE,
       ID_ULTIMA_ATTIVITA,
       to_char(DATA_ULTIMA_ATTIVITA, 'yyyymmddhh24miss'),
       COD_PROPOSTA,
       to_char(DATA_CESSAZIONE, 'yyyymmddhh24miss'),
       to_char(RRNG_DATA_BLOCCO_FATT, 'yyyymmddhh24miss'),
       RRNG_ESITO_BLOCCO,
       to_char(RRNG_DATA_SBLOCCO_FATT, 'yyyymmddhh24miss'),
       RRNG_ESITO_SBLOCCO,
       PASS_RES_BUS,
       PASS_BUS_RES,
       to_char(CNT_DATA_BLOCCO_FATT, 'yyyymmddhh24miss'),
       to_char(CNT_DATA_SBLOCCO_FATT, 'yyyymmddhh24miss'),
       FLAG_BLOCCO,
       FLAG_LETTURE_INS,
       ASSEGNAZIONE,
       TIPO_RICHIEDENTE,
       ID_ASS_CONCIL
       --,SR_CP_RAGIONE_SOCIALE                                                          
       --,SR_CP_REG_COMPET                                                               
       --,SR_CP_TELEFONO                                                                 
       --,SR_CP_EMAIL                                                                    
       --,s.SR_CP_FAX                                                                      
      ,
       ID_CONCIL_ASSOC,
       CCL_ASS_NOME_COGNOME,
       CCL_ASS_CELLULARE,
       CCL_ASS_TELEFONO,
       CCL_ASS_EMAIL,
       ID_CONCIL_SORGENIA,
       CCL_SORG_NOME_COGNOME,
       CCL_SORG_CELLULARE,
       CCL_SORG_TELEFONO,
       CCL_SORG_EMAIL,
       NUMERO_FATTURA,
       to_char(DATA_MANCATA_CONSEGNA, 'yyyymmddhh24miss'),
       CAUSALE_INESITO,
       DESTINATARIO,
       CAUSALE_ESITO_NEGATIVO,
       NUMERO_PROTOCOLLO,
       DATO_IVA_PRECEDENTE,
       DATO_IVA_NUOVO,
       to_char(DATA_INIZIO_ESENZIONE, 'yyyymmddhh24miss'),
       to_char(DATA_FINE_ESENZIONE, 'yyyymmddhh24miss'),
       RRMB_COD_ENTITA_FATTURABILE,
       METODO_PAGAMENTO,
       RRMB_INTESTATARIO_CC,
       CODICE_IBAN,
       AMPG_COD_ENTITA_FATTURABILE,
       MODALITA_PAGAMENTO,
       to_char(AMPG_DATA_INIZIO_VALIDITA, 'yyyymmddhh24miss'),
       MDP_PRIMARIO,
       COD_DOMICILIAZIONE,
       BANCA,
       FILIALE,
       COD_NAZIONE,
       CIN_EUROPEO,
       CIN,
       ABI,
       CAB,
       NUMERO_CC,
       IBAN,
       AMPG_INTESTATARIO_CC,
       CF_PI_INTESTATARIO_CC,
       INDIRIZZO_INTESTATARIO_CC,
       COMUNE_INTESTATARIO_CC,
       CAP_INTESTATARIO_CC,
       PROVINCIA_INTESTATARIO_CC,
       NOM_COGN_SOTTOSCR_RID,
       CF_SOTTOSCRITTORE_RID,
       STATO_DELEGA,
       APPOGGIO_BANCARIO_DISP,
       ID_PIANO,
       NUMERO_RATE,
       FREQUENZA_RATE,
       INTERVALLO_RATE,
       PIANO_RATE,
       CODICE_PIANO_RATE,
       SUB_RILEVANZA_CONT_SERV,
       MODIFICA_POTENZA,
       SUBENTRO_COMPLESSO,
       MDC_RILEVANZA_CONT_SERV,
       MDC_PRESENZA_CLIENTE_FINALE,
       SOLLEVAMENTO_PERSONE,
       INTERVENTO_GRUPPO_MISURA,
       MDC_REGISTRAZIONE_TELEFONICA,
       MDC_POTENZA_RICHIESTA,
       MDC_POTENZA_RICH_SUP_16_5,
       MDC_POTENZA_ATT_IMPEGNATA,
       MDC_POTENZA_ATT_DISPONIBILE,
       MDC_FRANCHIGIA,
       MDC_TENSIONE_RICHIESTA,
       MDC_TENSIONE_ATTUALE,
       MDC_MODULISTICA_CLIENTE,
       DESCRIZIONE_LAVORO,
       to_char(DATA_RICEZIONE_PREVENTIVO, 'yyyymmddhh24miss'),
       POD,
       TIPO_RICHIESTA,
       to_char(MDC_DATA_CESSIONE_PREVISTA, 'yyyymmddhh24miss'),
       STRUMENTO_REGISTRAZIONE,
       DIS_PRESENZA_CLIENTE_FINALE,
       DISATTIVAZIONE_FUORI_ORARIO,
       DIS_REGISTRAZIONE_TELEFONICA,
       DIS_MODULISTICA_CLIENTE,
       to_char(DIS_DATA_CESSIONE_PREVISTA, 'yyyymmddhh24miss'),
       to_char(DATA_CESSIONE_EFFETTIVA, 'yyyymmddhh24miss'),
       RECLAMO_SCRITTO,
       to_char(DATA_RICEZIONE_RICHIESTA, 'yyyymmddhh24miss'),
       to_char(DATA_INVIO_RISP_DEFINITIVA, 'yyyymmddhh24miss'),
       to_char(DATA_INVIO_RISP_PRELIMINARE, 'yyyymmddhh24miss'),
       to_char(DATA_INVIO_PRATICA_DISTR, 'yyyymmddhh24miss'),
       FLAG_RECLAMO_COMPLESSO,
       to_char(DATA_RICEZ_RISP_DISTR, 'yyyymmddhh24miss'),
       ALTRO_DESTINATARIO,
       to_char(DATA_DECORRENZA_RICHIESTA, 'yyyymmddhh24miss'),
       FLAG_LETTURE_INSERITE,
       FLAG_FATTURA_PAGATA,
       RFT_COD_FATTURA,
       to_char(DATA_ATTIVAZIONE_RICHIESTA, 'yyyymmddhh24miss'),
       to_char(DATA_CESSAZIONE_RICHIESTA, 'yyyymmddhh24miss'),
       RFC_COD_FATTURA,
       RFMC_POTENZA_ATTUALE,
       RFMC_POTENZA_ATT_IMPEGNATA,
       RFMC_POTENZA_ATT_DISPONIBILE,
       FASE_ATTUALE,
       RFMC_FRANCHIGIA,
       RFMC_TENSIONE_RICHIESTA,
       RFMC_TENSIONE_ATTUALE,
       RFMC_POTENZA_RICHIESTA,
       RFMC_POTENZA_RICH_SUP_16_5,
       FASE_RICHIESTA,
       PRODOTTO_APPLICATO,
       PRODOTTO_RICHIESTO,
       IVA_RICHIESTA,
       ACCISA_RICHIESTA,
       CAUSALE_ANAGRAFICA,
       to_char(AGF_DATA_INIZIO_VALIDITA, 'yyyymmddhh24miss'),
       TRIBUNALE_ISCRIZIONE,
       NUM_REG_TRIBUNALE,
       PROV_ISCR_CAM_COMM,
       REGISTRO_IMPRESE,
       RIEMISSIONE_FATTURA DINIEGO_MARKETING
  from dbi_user.ifc_sap_crm_sr s
 where length(s.categoria_1 || s.categoria_2 || s.categoria_3) = 12
   and s.categoria_1 <> 'N.A.'
   and s.codice_cliente in
       (select oldkey from z_temksv where object = 'PARTNER')
 group by ID_SR,
          TIPOLOGIA_SR,
          ID_SR_PADRE,
          ID_INTERAZIONE,
          CATEGORIA_1,
          CATEGORIA_2,
          CATEGORIA_3,
          STATO_SR,
          SEGMENTO_CLIENTE,
          CANALE_INGAGGIO,
          USER_ID_CREATORE,
          to_char(DATA_CREAZIONE, 'yyyymmddhh24miss'),
          MOTIVO_STATO,
          to_char(DATA_CHIUSURA, 'yyyymmddhh24miss'),
          to_char(DATA_ASSEGNAZIONE, 'yyyymmddhh24miss'),
          to_char(DATA_SCADENZA, 'yyyymmddhh24miss'),
          NUMERO_DOCUMENTI,
          TIPO_CORRISPONDENZA,
          TIPO_SERVIZIO,
          NOTE_CALL_CENTER,
          NOTE_CALL_CENTER_2,
          NOTE_RISERVATE_BOS,
          NOTE_RISERVATE_BOS_2,
          ATTIVITA,
          ATTIVITA_2,
          ATTIVITA_3,
          ATTIVITA_4,
          IDENTIFICATIVO_OPT,
          UTENTE_CREATORE,
          GRUPPO_CREATORE,
          CANALE,
          ID_PUNTO,
          PUNTO_FORNITURA,
          RICHIESTA_INFO,
          ID_TICKET,
          CODICE_CLIENTE,
          RAGIONE_SOCIALE,
          INDIRIZZO_MAIL,
          INDIRIZZO,
          CAP,
          COMUNE,
          PROVINCIA,
          TELEFONO,
          FAX,
          ID_PERSONA_CONTATTO,
          NOME_CONT,
          COGNOME_CONT,
          EMAIL_CONT,
          TEL_CONT,
          CELL_CONT,
          RIPROPOSIZIONE,
          P_IVA,
          COD_FISCALE,
          ID_ULTIMA_ATTIVITA,
          to_char(DATA_ULTIMA_ATTIVITA, 'yyyymmddhh24miss'),
          COD_PROPOSTA,
          to_char(DATA_CESSAZIONE, 'yyyymmddhh24miss'),
          to_char(RRNG_DATA_BLOCCO_FATT, 'yyyymmddhh24miss'),
          RRNG_ESITO_BLOCCO,
          to_char(RRNG_DATA_SBLOCCO_FATT, 'yyyymmddhh24miss'),
          RRNG_ESITO_SBLOCCO,
          PASS_RES_BUS,
          PASS_BUS_RES,
          to_char(CNT_DATA_BLOCCO_FATT, 'yyyymmddhh24miss'),
          to_char(CNT_DATA_SBLOCCO_FATT, 'yyyymmddhh24miss'),
          FLAG_BLOCCO,
          FLAG_LETTURE_INS,
          ASSEGNAZIONE,
          TIPO_RICHIEDENTE,
          ID_ASS_CONCIL
          --,SR_CP_RAGIONE_SOCIALE                                                          
          --,SR_CP_REG_COMPET                                                               
          --,SR_CP_TELEFONO                                                                 
          --,SR_CP_EMAIL                                                                    
          --,s.SR_CP_FAX                                                                      
         ,
          ID_CONCIL_ASSOC,
          CCL_ASS_NOME_COGNOME,
          CCL_ASS_CELLULARE,
          CCL_ASS_TELEFONO,
          CCL_ASS_EMAIL,
          ID_CONCIL_SORGENIA,
          CCL_SORG_NOME_COGNOME,
          CCL_SORG_CELLULARE,
          CCL_SORG_TELEFONO,
          CCL_SORG_EMAIL,
          NUMERO_FATTURA,
          to_char(DATA_MANCATA_CONSEGNA, 'yyyymmddhh24miss'),
          CAUSALE_INESITO,
          DESTINATARIO,
          CAUSALE_ESITO_NEGATIVO,
          NUMERO_PROTOCOLLO,
          DATO_IVA_PRECEDENTE,
          DATO_IVA_NUOVO,
          to_char(DATA_INIZIO_ESENZIONE, 'yyyymmddhh24miss'),
          to_char(DATA_FINE_ESENZIONE, 'yyyymmddhh24miss'),
          RRMB_COD_ENTITA_FATTURABILE,
          METODO_PAGAMENTO,
          RRMB_INTESTATARIO_CC,
          CODICE_IBAN,
          AMPG_COD_ENTITA_FATTURABILE,
          MODALITA_PAGAMENTO,
          to_char(AMPG_DATA_INIZIO_VALIDITA, 'yyyymmddhh24miss'),
          MDP_PRIMARIO,
          COD_DOMICILIAZIONE,
          BANCA,
          FILIALE,
          COD_NAZIONE,
          CIN_EUROPEO,
          CIN,
          ABI,
          CAB,
          NUMERO_CC,
          IBAN,
          AMPG_INTESTATARIO_CC,
          CF_PI_INTESTATARIO_CC,
          INDIRIZZO_INTESTATARIO_CC,
          COMUNE_INTESTATARIO_CC,
          CAP_INTESTATARIO_CC,
          PROVINCIA_INTESTATARIO_CC,
          NOM_COGN_SOTTOSCR_RID,
          CF_SOTTOSCRITTORE_RID,
          STATO_DELEGA,
          APPOGGIO_BANCARIO_DISP,
          ID_PIANO,
          NUMERO_RATE,
          FREQUENZA_RATE,
          INTERVALLO_RATE,
          PIANO_RATE,
          CODICE_PIANO_RATE,
          SUB_RILEVANZA_CONT_SERV,
          MODIFICA_POTENZA,
          SUBENTRO_COMPLESSO,
          MDC_RILEVANZA_CONT_SERV,
          MDC_PRESENZA_CLIENTE_FINALE,
          SOLLEVAMENTO_PERSONE,
          INTERVENTO_GRUPPO_MISURA,
          MDC_REGISTRAZIONE_TELEFONICA,
          MDC_POTENZA_RICHIESTA,
          MDC_POTENZA_RICH_SUP_16_5,
          MDC_POTENZA_ATT_IMPEGNATA,
          MDC_POTENZA_ATT_DISPONIBILE,
          MDC_FRANCHIGIA,
          MDC_TENSIONE_RICHIESTA,
          MDC_TENSIONE_ATTUALE,
          MDC_MODULISTICA_CLIENTE,
          DESCRIZIONE_LAVORO,
          to_char(DATA_RICEZIONE_PREVENTIVO, 'yyyymmddhh24miss'),
          POD,
          TIPO_RICHIESTA,
          to_char(MDC_DATA_CESSIONE_PREVISTA, 'yyyymmddhh24miss'),
          STRUMENTO_REGISTRAZIONE,
          DIS_PRESENZA_CLIENTE_FINALE,
          DISATTIVAZIONE_FUORI_ORARIO,
          DIS_REGISTRAZIONE_TELEFONICA,
          DIS_MODULISTICA_CLIENTE,
          to_char(DIS_DATA_CESSIONE_PREVISTA, 'yyyymmddhh24miss'),
          to_char(DATA_CESSIONE_EFFETTIVA, 'yyyymmddhh24miss'),
          RECLAMO_SCRITTO,
          to_char(DATA_RICEZIONE_RICHIESTA, 'yyyymmddhh24miss'),
          to_char(DATA_INVIO_RISP_DEFINITIVA, 'yyyymmddhh24miss'),
          to_char(DATA_INVIO_RISP_PRELIMINARE, 'yyyymmddhh24miss'),
          to_char(DATA_INVIO_PRATICA_DISTR, 'yyyymmddhh24miss'),
          FLAG_RECLAMO_COMPLESSO,
          to_char(DATA_RICEZ_RISP_DISTR, 'yyyymmddhh24miss'),
          ALTRO_DESTINATARIO,
          to_char(DATA_DECORRENZA_RICHIESTA, 'yyyymmddhh24miss'),
          FLAG_LETTURE_INSERITE,
          FLAG_FATTURA_PAGATA,
          RFT_COD_FATTURA,
          to_char(DATA_ATTIVAZIONE_RICHIESTA, 'yyyymmddhh24miss'),
          to_char(DATA_CESSAZIONE_RICHIESTA, 'yyyymmddhh24miss'),
          RFC_COD_FATTURA,
          RFMC_POTENZA_ATTUALE,
          RFMC_POTENZA_ATT_IMPEGNATA,
          RFMC_POTENZA_ATT_DISPONIBILE,
          FASE_ATTUALE,
          RFMC_FRANCHIGIA,
          RFMC_TENSIONE_RICHIESTA,
          RFMC_TENSIONE_ATTUALE,
          RFMC_POTENZA_RICHIESTA,
          RFMC_POTENZA_RICH_SUP_16_5,
          FASE_RICHIESTA,
          PRODOTTO_APPLICATO,
          PRODOTTO_RICHIESTO,
          IVA_RICHIESTA,
          ACCISA_RICHIESTA,
          CAUSALE_ANAGRAFICA,
          to_char(AGF_DATA_INIZIO_VALIDITA, 'yyyymmddhh24miss'),
          TRIBUNALE_ISCRIZIONE,
          NUM_REG_TRIBUNALE,
          PROV_ISCR_CAM_COMM,
          REGISTRO_IMPRESE,
          RIEMISSIONE_FATTURA,
          DINIEGO_MARKETING
'''
#inizializzazione e apertura file di log
date=datetime.datetime.now()
htmlMode=''
log = LogManager('E_Sr', Constants.getDebugMode(),date,htmlMode)
#creazione oggetto di connessione Oracle
#conn = ConnectionManager('E_Sr',log)
#inizializzazione e apertura file CSV
mycsv = CsvManager('service_requests',';',False)
#nome programma
#log.testata("creazione csv SR" )

#cursor = conn.conn.cursor()
cur_s1 = conn.cursor()
cur_s1.execute("ALTER SESSION SET NLS_DATE_FORMAT = 'YYYYMMDD'")
cur_s1.execute("ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYYMMDDHH24MISS'")
#cur_s1.execute("ALTER SESSION SET NLS_TIME_FORMAT = 'HHMMSS'")
cur_s1.execute("SELECT * FROM v$nls_parameters WHERE REGEXP_LIKE(parameter, 'NLS_(DATE|TIME).*')")
for rec_s1 in cur_s1:
                    print("PARAMETER: " + rec_s1[0] + " VALUE: " + rec_s1[1])
#select principale
cur_s1.execute(stat_finale)

i=0      
ifx = '\t'
#loop sul resultset
linesToWrite = []
yy=1
ctrEnde=0
ctrTota=0
with open(mycsv.csvFileName.replace('$s',str(yy)), 'wb') as f:
    csv.register_dialect('csv', delimiter=';',quotechar="'", quoting=csv.QUOTE_MINIMAL)
    dialect = csv.get_dialect('csv')
    writer = csv.writer(f,dialect)
    
    for record_s1 in cur_s1:
        #print record_s1
        w_key = record_s1[0]
        record_l1 = list(record_s1)
        #del record_l1[-1]
        linesToWrite.append(record_l1)
        ctrTota+=1
    writer.writerows(linesToWrite)
    linesToWrite=[]
#chiusura componenti
cur_s1.close()
#cursor.close()
print "Sono state scritte ",ctrTota," righe."
conn.close()
log.close()